export enum ComponentName {
  THREE_COLUMN_GRID = `three-column-grid`,
  COLLAGE_WITH_LINK = `collage-with-link`,
  COLLAGE_WITH_TITLE = `collage-with-title`,
  FOOTER = `footer`,
  HEADER = `header`,
  MOBILE_MENU = `mobile-menu`,
  HERO = `hero`,
  SHOWCASE_GRID_WITH_FOUR_COLUMNS = `showcase-grid-with-four-columns`,
  SHOWCASE_GRID_WITH_THREE_COLUMNS = `showcase-grid-with-three-columns`,
  SHOWCASE_GRID_WITH_MARKDOWN_COLUMN = `showcase-grid-with-markdown-column`,
  FEATURED_CARDS_LIST = `featured-cards-list`,
  SIGNPOST_MULTIPLE = `signpost-multiple`,
  SINGLE_IMAGE = `single-image`,
  FORM_BLOCK = `form-block`,
  SUBMITTED_FORM_BLOCK = `submitted-form-block`,
  COOKIE = `cookie`,
  NOT_FOUND = `not-found`,
  FORM_MODAL = `form-modal`,
  SUBMITTED_FORM_MODAL = `submitted-form-modal`,
}
